services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  caddy:
    image: caddy:2.8.4
    ports:
      - "9080:80"
    environment:
      - DJANGO_ADMIN_PAGE_NAME=${DJANGO_ADMIN_PAGE_NAME}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_data:/www/static
      - media_data:/www/media
    restart: always

  backend:
    build: ./backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ADMIN_PAGE_NAME=${DJANGO_ADMIN_PAGE_NAME}
      - ALLOWED_HOST=127.0.0.1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - EMAIL_PREFIX=${EMAIL_PREFIX}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - HEADLESS_URL_ROOT=http://127.0.0.1:9080
      - ORCID_BASE_DOMAIN=sandbox.orcid.org
      - ACCOUNT_DEFAULT_HTTP_PROTOCOL=http
      - LOG_FILE=/dev/null
      - DEBUG=True
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_FIRST_NAME=${DJANGO_SUPERUSER_FIRST_NAME}
      - DJANGO_SUPERUSER_LAST_NAME=${DJANGO_SUPERUSER_LAST_NAME}
      - DJANGO_SUPERUSER_INSTITUTE=${DJANGO_SUPERUSER_INSTITUTE}
      - TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_SECRET_KEY=${PAYPAL_SECRET_KEY}
      - PAYPAL_API_URL=https://api-m.sandbox.paypal.com
      - OPENEXCHANGERATES_APP_ID=${OPENEXCHANGERATES_APP_ID}
    ports:
      - "8090:8080"
    volumes:
      - ./backend:/app
      - static_data:/app/static
      - media_data:/app/media
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
        - TOSS_CLIENT_KEY=${TOSS_CLIENT_KEY}
        - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    environment:
      - ALLOWED_HOST=${HOST}
      - ADMIN_PAGE_NAME=${ADMIN_PAGE_NAME}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - TOSS_CLIENT_KEY=${TOSS_CLIENT_KEY}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - DEBUG=True
      - BODY_SIZE_LIMIT=2097152
    volumes:
      - ./frontend:/app
    restart: always

  rabbitmq:
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  celery:
    build: ./backend
    command: sh -c "celery -A backend worker -l info"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_PREFIX=${EMAIL_PREFIX}
    volumes:
      - ./backend:/app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

  celery-beat:
    build: ./backend
    command: sh -c "celery -A backend beat -l info"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_PREFIX=${EMAIL_PREFIX}
    volumes:
      - ./backend:/app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "4"

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  static_data:
  media_data: