# Generated by Django 5.2 on 2025-04-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='department',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='job_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
