# Generated by Django 5.1 on 2025-06-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attendee_department_alter_attendee_job_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSiteAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('last_name', models.CharField(max_length=1000)),
                ('institute', models.CharField(max_length=1000)),
                ('job_title', models.CharField(blank=True, max_length=1000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onsite_attendees', to='main.event')),
            ],
        ),
    ]
