# Generated by Django 5.1 on 2026-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verification_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'verification_key'], name='main_emailv_email_ef5263_idx')],
            },
        ),
    ]
