# Generated by Django 5.1 on 2026-01-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emailverificationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='korean_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
