# Generated by Django 5.1 on 2026-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_venue_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
