# Generated by Django 5.1 on 2026-01-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_event_venue_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('symposium', 'Symposium'), ('meeting', 'Meeting'), ('conference', 'Conference')], default='conference', max_length=50),
        ),
    ]
