# Generated by Django 5.1 on 2026-01-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
