# Generated by Django 5.1 on 2026-01-27 19:49

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_main_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='korean_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_languages',
            field=models.JSONField(default=main.models.default_main_languages),
        ),
    ]
