# Generated by Django 5.1 on 2026-01-28 12:58

import django.db.models.deletion
from django.db import migrations, models


def migrate_user_institutes(apps, _schema_editor):
    """
    Migrate existing User.institute CharField data to Institution ForeignKey
    """
    User = apps.get_model('main', 'User')
    Institution = apps.get_model('main', 'Institution')

    for user in User.objects.all():
        if user.institute_old:
            # Get or create institution from the old institute string
            institution, _created = Institution.objects.get_or_create(
                name_en=user.institute_old,
                defaults={'name_ko': ''}
            )
            user.institute_new = institution
            user.save()


def reverse_migrate_user_institutes(apps, _schema_editor):
    """
    Reverse migration: copy institute_new back to institute_old as string
    """
    User = apps.get_model('main', 'User')

    for user in User.objects.all():
        if user.institute_new:
            user.institute_old = user.institute_new.name_en
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_attendee_korean_name_alter_event_main_languages'),
    ]

    operations = [
        # Step 1: Rename old institute field to institute_old
        migrations.RenameField(
            model_name='user',
            old_name='institute',
            new_name='institute_old',
        ),
        # Step 2: Add new ForeignKey field
        migrations.AddField(
            model_name='user',
            name='institute_new',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='main.institution'
            ),
        ),
        # Step 3: Migrate data from institute_old to institute_new
        migrations.RunPython(
            migrate_user_institutes,
            reverse_migrate_user_institutes
        ),
        # Step 4: Remove old institute_old field
        migrations.RemoveField(
            model_name='user',
            name='institute_old',
        ),
        # Step 5: Rename institute_new to institute
        migrations.RenameField(
            model_name='user',
            old_name='institute_new',
            new_name='institute',
        ),
    ]
