# Generated by Django 5.1 on 2026-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_user_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='institute_ko',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
