# Generated by Django 5.1 on 2026-01-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_attendee_institute_ko'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_ko',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
