# Generated by Django 5.1 on 2026-01-30 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_event_venue_ko'),
    ]

    operations = [
        # Rename the old organizers field to organizers_old
        migrations.RenameField(
            model_name='event',
            old_name='organizers',
            new_name='organizers_old',
        ),
        # Create the new M2M field
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        # Remove the old field (data will be lost, but we'll provide instructions to manually migrate if needed)
        migrations.RemoveField(
            model_name='event',
            name='organizers_old',
        ),
    ]
