# Generated by Django 5.1 on 2026-01-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_event_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onsiteattendee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='onsiteattendee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='onsiteattendee',
            name='middle_initial',
        ),
    ]
