# Generated by Django 5.1 on 2026-01-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_first_name_onsiteattendee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteattendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
