# Generated by Django 5.1 on 2026-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_event_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
