# Generated by Django 5.1 on 2026-01-31 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_event_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_template_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template_certificate', to='main.emailtemplate'),
        ),
    ]
