# Generated by Django 5.1 on 2026-01-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_event_email_template_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
