# Generated by Django 5.1 on 2026-02-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('business_registration_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('representative', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='approval_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='card_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='installment',
            field=models.CharField(choices=[('single', '일시불'), ('2', '2개월'), ('3', '3개월'), ('4', '4개월'), ('5', '5개월'), ('6', '6개월'), ('7', '7개월'), ('8', '8개월'), ('9', '9개월'), ('10', '10개월'), ('11', '11개월'), ('12', '12개월')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='vat',
            field=models.IntegerField(default=0),
        ),
    ]
