# Generated by Django 5.1 on 2026-02-01 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_businesssettings_paymenthistory_approval_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='approval_number',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='vat',
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=20)),
                ('vat', models.IntegerField(default=0)),
                ('approval_number', models.CharField(max_length=50)),
                ('installment', models.CharField(choices=[('single', '일시불'), ('2', '2개월'), ('3', '3개월'), ('4', '4개월'), ('5', '5개월'), ('6', '6개월'), ('7', '7개월'), ('8', '8개월'), ('9', '9개월'), ('10', '10개월'), ('11', '11개월'), ('12', '12개월')], default='single', max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_transaction', to='main.paymenthistory')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
