# Generated by Django 5.1 on 2026-02-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_paymenthistory_approval_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('card', '신용카드'), ('transfer', '계좌이체'), ('cash', '현금')], default='card', max_length=20),
        ),
    ]
