# Generated by Django 5.1 on 2026-02-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_paymenthistory_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
