# Generated by Django 5.1 on 2026-02-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_add_payment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='toss_order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='toss_payment_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
