# Generated by Django 5.1 on 2026-02-01 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_paymenthistory_toss_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_department',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_first_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_institute',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_institute_ko',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_job_title',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_korean_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_last_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='attendee_nationality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='event_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='attendee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='main.attendee'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='main.event'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
