# Generated by Django 5.1 on 2026-02-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_paymenthistory_attendee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
