# Generated by Django 5.1 on 2026-02-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_add_order_id_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardTransaction',
        ),
    ]
