# Generated by Django 5.1 on 2026-02-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_cardtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='order_id',
        ),
    ]
