# Generated by Django 5.1 on 2026-02-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_order_id_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='main.attendee'),
        ),
    ]
