# Generated by Django 5.1 on 2026-02-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_user_from_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='event_organizers_en',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='event_organizers_ko',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='event_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='event_venue',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='event_venue_ko',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
