# Generated by Django 5.1 on 2026-02-01 10:27

from django.db import migrations


def backfill_event_data(apps, schema_editor):
    """Backfill event data for existing payment records."""
    PaymentHistory = apps.get_model('main', 'PaymentHistory')

    def get_organizers_en(event):
        """Format organizers in English."""
        parts = []
        for org in event.organizers.all():
            name = f"{org.first_name} {org.last_name}".strip()
            if org.institute:
                # institute is a ForeignKey, so access the related object directly
                inst = org.institute
                if inst and inst.name_en:
                    name += f" ({inst.name_en})"
            parts.append(name)
        return ", ".join(parts)

    def get_organizers_ko(event):
        """Format organizers in Korean."""
        parts = []
        for org in event.organizers.all():
            name = org.korean_name if org.korean_name else f"{org.first_name} {org.last_name}".strip()
            if org.institute:
                inst = org.institute
                if inst:
                    inst_name = inst.name_ko or inst.name_en
                    if inst_name:
                        name += f" ({inst_name})"
            parts.append(name)
        return ", ".join(parts)

    for payment in PaymentHistory.objects.filter(event__isnull=False).select_related('event'):
        event = payment.event
        payment.event_name = event.name or ''
        payment.event_start_date = event.start_date
        payment.event_end_date = event.end_date
        payment.event_venue = event.venue or ''
        payment.event_venue_ko = event.venue_ko or ''
        payment.event_organizers_en = get_organizers_en(event)
        payment.event_organizers_ko = get_organizers_ko(event)
        payment.save(update_fields=[
            'event_name', 'event_start_date', 'event_end_date',
            'event_venue', 'event_venue_ko', 'event_organizers_en', 'event_organizers_ko'
        ])


def reverse_backfill(apps, schema_editor):
    """Reverse migration - clear the copied event data."""
    pass  # No action needed on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_add_event_fields_to_paymenthistory'),
    ]

    operations = [
        migrations.RunPython(backfill_event_data, reverse_backfill),
    ]
