# Generated by Django 5.1 on 2026-02-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', '카드'), ('transfer', '계좌이체'), ('cash', '현금')], max_length=50)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('vat', models.IntegerField(default=0)),
                ('approval_number', models.CharField(blank=True, max_length=50)),
                ('installment', models.CharField(blank=True, default='single', max_length=20)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_transaction', to='main.paymenthistory')),
            ],
        ),
    ]
