# Generated by Django 5.1 on 2026-02-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_manualtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtransaction',
            name='supply_amount',
            field=models.IntegerField(default=0),
        ),
    ]
