# Generated by Django 5.1 on 2026-02-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_manualtransaction_supply_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualtransaction',
            name='transaction_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualtransaction',
            name='transaction_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
