# Generated by Django 5.1 on 2026-02-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_manualtransaction_transaction_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_address_ko',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
