# Generated by Django 5.1 on 2026-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_add_venue_address_ko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='abstract',
            name='is_oral',
        ),
        migrations.AddField(
            model_name='abstract',
            name='type',
            field=models.CharField(choices=[('speaker', 'Speaker'), ('poster', 'Poster')], default='poster', max_length=20),
        ),
        migrations.AddField(
            model_name='abstract',
            name='wants_short_talk',
            field=models.BooleanField(default=False),
        ),
    ]
