# Generated by Django 5.1 on 2026-02-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_termsofservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
