# Generated by Django 5.1 on 2026-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_attendee_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nametag_orientation',
            field=models.CharField(default='portrait', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='nametag_paper_height',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='nametag_paper_width',
            field=models.FloatField(default=90),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
