# Generated by Django 5.1 on 2026-02-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_add_nametag_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
