# Generated by Django 5.1 on 2026-02-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_businesssettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='abstract_submission_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='external_abstract_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
