# Generated by Django 5.1 on 2026-02-08 05:09

import string
import random
from django.db import migrations, models


def generate_onsite_codes(apps, schema_editor):
    """Generate onsite codes for existing events that don't have one."""
    Event = apps.get_model('main', 'Event')
    chars = string.ascii_uppercase + string.digits
    for event in Event.objects.filter(onsite_code=''):
        event.onsite_code = ''.join(random.choices(chars, k=6))
        event.save(update_fields=['onsite_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_event_external_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='onsite_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.RunPython(generate_onsite_codes, migrations.RunPython.noop),
    ]
