# Generated by Django 5.1 on 2026-02-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_event_onsite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteattendee',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
