# Generated by Django 5.1 on 2026-02-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_onsite_attendee_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
