# Generated by Django 5.1 on 2026-02-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_attendee_is_attended'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='IEUM', max_length=200)),
                ('site_description', models.TextField(blank=True, default='An open-source conference management system for organizing scientific conferences. Manage event registrations, abstract submissions, and attendee workflows seamlessly.')),
                ('site_keywords', models.CharField(blank=True, default='conference management, event registration, abstract submission, scientific conference, academic event', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
