# Generated by Django 5.1 on 2026-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customquestion',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='customquestion',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
